---
--- Generated by Luanalysis
--- Created by wangyujie.
--- DateTime: 2025-01-12 10:56
---
-- 比较线程标识与锁中的标示是否一致
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del',KEYS[1])
end
return 0